//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Военный_округ_Батталов
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MilitaryDistrictEntities : DbContext
    {
        public MilitaryDistrictEntities()
            : base("name=MilitaryDistrictEntities")
        {
        }

        private static MilitaryDistrictEntities _context;

        public static MilitaryDistrictEntities GetContext()
        {
            if( _context == null)
            {
                _context = new MilitaryDistrictEntities();
            }

            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Award> Award { get; set; }
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Personnel> Personnel { get; set; }
        public virtual DbSet<Personnel_Award> Personnel_Award { get; set; }
        public virtual DbSet<Personnel_Event> Personnel_Event { get; set; }
        public virtual DbSet<Platoon> Platoon { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
    }
}
