//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Военный_округ_Батталов
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel_Award
    {
        public int Id_record { get; set; }
        public int Id_personnel { get; set; }
        public int Id_award { get; set; }
    
        public virtual Award Award { get; set; }
        public virtual Personnel Personnel { get; set; }
    }
}
