//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Военный_округ_Батталов
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personnel()
        {
            this.Personnel_Event = new HashSet<Personnel_Event>();
            this.Personnel_Award = new HashSet<Personnel_Award>();
        }
    
        public int Id_personnel { get; set; }
        public int Id_platoon { get; set; }
        public string Last_name { get; set; }
        public string First_name { get; set; }
        public string Position { get; set; }
        public int Birth_year {  get; set; }
        
        public int Start_service_year { get; set; }
        public Nullable<int> Service_experience_years { get; set; }
        public string Images_personnel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personnel_Event> Personnel_Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personnel_Award> Personnel_Award { get; set; }
        public virtual Platoon Platoon { get; set; }
    }
}
