//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Военный_округ_Батталов
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PersonnelWithPlatoonAndUnit
    {
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Название_роты { get; set; }
        public int Код_части { get; set; }
    }
}
